### ISSUE TITLE
How to use SAPADeform  to modify the upsampling stages

### ISSUE THREAD

**Issue by Hello-Worldd** [tiny-smart/sapa#1]
First of all, thank you for your work, but I have some questions about this

```python
 x = torch.randn(2, 16, 4, 6).to('cuda')
 y = torch.randn(2, 16, 8, 12).to('cuda')
 sapa = SAPADeform(16).to('cuda')
 print(sapa(y, x).shape)
```
From the code, it can be seen that SAPADeform requires **two inputs**.
But upsampling only requires **one input**. 
So I want to know how to use SAPADeform  to modify the upsampling stages

**Comment by poppuppy** [comment]
SAPA needs a high-res guidance feature to conduct upsampling. For example, if you want to upsample the 'res5' feature in ResNet, then 'res4' may serve as the guidance feature. For more information you can have a look at the paper.
