### ISSUE TITLE
ModuleNotFoundError: No module named 'dqk'

### ISSUE THREAD

**Issue by f1shihang** [tiny-smart/sapa#4]
Hello, thank you for your work.
Error running sapadeform.py file：ModuleNotFoundError: No module named 'dqk'.
I can't find 'dqk' and 'dav' modules in the file.Can you tell me how to do that？
thanks again.

**Comment by poppuppy** [comment]
Hello. Have you complied the operator (As python setup.py develop)?

**Comment by f1shihang** [comment]
I'm sorry to see your reply so late. It has already been implemented. Thank you again！

**Comment by poppuppy** [comment]
Ok. Thanks for your interest.
